/*export { BaseUser } from "./src/classes/BaseUser.ts"
export { CommentAuthor } from "./src/classes/CommentAuthor.ts"
export { News } from "./src/classes/News.ts"
export { Project } from "./src/classes/Project.ts"
export { ProjectAuthor } from "./src/classes/ProjectAuthor.ts"
export { ProjectComment } from "./src/classes/ProjectComment.ts"
export { ProjectFavouriteStatus } from "./src/classes/ProjectFavouriteStatus.ts"
export { ProjectFavouriteStatus as ProjectFavoriteStatus} from "./src/classes/ProjectFavouriteStatus.ts"
export { ProjectLoveStatus } from "./src/classes/ProjectLoveStatus.ts"
export { SessionUser } from "./src/classes/SessionUser.ts"
export { Studio } from "./src/classes/Studio.ts"
export { User } from "./src/classes/User.ts"
export { UserProfile } from "./src/classes/UserProfile.ts"

export { ClientAuthorisation } from "./src/interfaces/ClientAuthorisation.ts"
export { ClientOptions } from "./src/interfaces/ClientOptions.ts"
export { ClientSession } from "./src/interfaces/ClientSession.ts"
export { CookieObject } from "./src/interfaces/CookieObject.ts"
export { ProfilePictureSizes } from "./src/interfaces/ProfilePictureSizes.ts"
export { ProjectHistory } from "./src/interfaces/ProjectHistory.ts"
export { ProjectRemixNode } from "./src/interfaces/ProjectRemixNode.ts"
export { ProjectStats } from "./src/interfaces/ProjectStats.ts"
export { ProjectThumbnailSizes } from "./src/interfaces/ProjectThumbnailSizes.ts"
export { QueryObject } from "./src/interfaces/QueryObject.ts"
export { RequestHeaders } from "./src/interfaces/RequestHeaders.ts"
export { RequestOptions } from "./src/interfaces/RequestOptions.ts"
export { SessionFlags } from "./src/interfaces/SessionFlags.ts"
export { SessionPermissions } from "./src/interfaces/SessionPermissions.ts"
export { StudioHistory } from "./src/interfaces/StudioHistory.ts"
export { StudioStats } from "./src/interfaces/StudioStats.ts"*/

export { ScratchClient } from "./src/Client.ts"